version: '3.8'

services:
  mariadb-peluqueria:
    image: mariadb:latest
    container_name: mariadb-peluqueria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: peluqueriaDB
      MYSQL_USER: peluqueria
      MYSQL_PASSWORD: pswpeluqueria
    ports:
      - "3310:3306"
    volumes:
      - ./data:/var/lib/mysql
