version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-peluqueria
    restart: always
    environment:
      MYSQL_DATABASE: peluqueria
      MYSQL_USER: pelu
      MYSQL_PASSWORD: pelu123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
